### ISSUE TITLE
Toggle comment not working in moonscript.

### ISSUE THREAD

**Issue by harrisyu** [AlRado/Sublime-TIC-80#2]
Toggle comment not working in moonscript.

**Comment by AlRado** [comment]
I do not understand what kind of comments not working, can you give an example?

**Comment by harrisyu** [comment]
In sublime text 3:
1.select some lines;
2.click on menu edit->comment->toggle comment.
Works fine in .lua file, but nothing happen in .moon.
The selected lines should have been commented.

**Comment by AlRado** [comment]
I realized this is working a standard package for LUA. If you disable it - such comments in the Lua file will not work. I'll figure out how to add this feature to your package.
